"use client";
import { useMemo, useState } from "react";

type View = "overview" | "catalog" | "pricing" | "stock" | "reports" | "public";
const products = [
  { name:"Premium Sardines 155g", brand:"555", category:"Canned Goods", price:32.5, stock:24, status:"In stock" },
  { name:"Instant Coffee 3-in-1", brand:"Nescafé", category:"Beverages", price:8.5, stock:7, status:"Low stock" },
  { name:"Laundry Detergent 65g", brand:"Tide", category:"Household", price:14, stock:42, status:"In stock" },
  { name:"Brown Sugar 1kg", brand:"Local", category:"Pantry", price:78, stock:0, status:"Out of stock" },
];
const movements = [
  ["10:42 AM","SALE","Premium Sardines 155g","-2","Staff"],
  ["10:15 AM","RESTOCK","Laundry Detergent 65g","+24","Manager"],
  ["Yesterday","ADJUSTMENT","Instant Coffee 3-in-1","-1","Owner"],
];
function Icon({name}:{name:string}) {
  const p:Record<string,string>={grid:"M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z",box:"M4 7.5 12 3l8 4.5v9L12 21l-8-4.5zM4 7.5l8 4.5 8-4.5M12 12v9",tag:"m20 13-7 7-10-10V4h6l11 9ZM7.5 8.5h.01",bars:"M5 20V10M12 20V4M19 20v-7",chart:"M4 19V5M4 19h16M7 15l3-4 3 2 4-6",search:"m20 20-4.5-4.5M10.5 17a6.5 6.5 0 1 1 0-13 6.5 6.5 0 0 1 0 13Z",arrow:"M5 12h14M13 6l6 6-6 6",plus:"M12 5v14M5 12h14",bell:"M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"};
  return <svg viewBox="0 0 24 24" className="icon"><path d={p[name]}/></svg>;
}
export default function Home(){
  const [view,setView]=useState<View>("overview"),[query,setQuery]=useState("");
  const filtered=useMemo(()=>products.filter(p=>[p.name,p.brand,p.category].join(" ").toLowerCase().includes(query.toLowerCase())),[query]);
  const nav=[["overview","Overview","grid"],["catalog","Catalog & Items","box"],["pricing","Pricing","tag"],["stock","Stock","bars"],["reports","Reports","chart"]] as const;
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><strong>SME MIS</strong><span>Price & Stock Control</span></div></div><nav><p className="nav-label">Workspace</p>{nav.map(([id,label,icon])=><button key={id} className={view===id?"nav-item active":"nav-item"} onClick={()=>setView(id)}><Icon name={icon}/><span>{label}</span></button>)}<p className="nav-label nav-gap">Customer</p><button className={view==="public"?"nav-item active":"nav-item"} onClick={()=>setView("public")}><Icon name="search"/><span>Public Price Lookup</span></button></nav><div className="sidebar-bottom"><div className="store-mini"><i className="status-dot"/><div><strong>Sample Store</strong><small>Active business</small></div></div><div className="user-mini"><div className="avatar">MA</div><div><strong>Mikie Ann</strong><small>Owner</small></div><span>•••</span></div></div></aside><section className="content"><header className="topbar"><div className="mobile-brand"><div className="brand-mark">S</div><strong>SME MIS</strong></div><div className="crumb">Sample Store <span>/</span> {view==="overview"?"Overview":nav.find(n=>n[0]===view)?.[1]??"Public Price Lookup"}</div><div className="top-actions"><button className="icon-button"><Icon name="bell"/></button><div className="avatar">MA</div></div></header><div className="page">{view==="overview"&&<Overview setView={setView}/>} {view==="catalog"&&<Catalog filtered={filtered} query={query} setQuery={setQuery}/>} {view==="pricing"&&<Pricing/>} {view==="stock"&&<Stock/>} {view==="reports"&&<Reports/>} {view==="public"&&<PublicLookup/>}</div></section></main>;
}
function Overview({setView}:{setView:(v:View)=>void}){return <><div className="hero-row"><div><p className="eyebrow">STORE OVERVIEW</p><h1>Good morning, Mikie.</h1><p className="muted">A clear view of prices, stock, and store activity.</p></div><button className="primary" onClick={()=>setView("catalog")}><Icon name="plus"/> Add item</button></div><div className="metric-grid"><Metric label="Active items" value="126" detail="+8 this month"/><Metric label="Price changes" value="9" detail="Last 7 days"/><Metric label="Low stock" value="7" detail="Needs attention" warning/><Metric label="Out of stock" value="3" detail="Currently unavailable"/></div><div className="dashboard-grid"><section className="panel"><Head title="Today's stock activity" sub="Recent movements across your items" action="View stock" onClick={()=>setView("stock")}/><div className="movement-list">{movements.map(m=><Movement key={m.join("-")} m={m}/>)}</div></section><section className="panel"><Head title="Stock alerts" sub="Items below reorder level"/><div className="alert-list"><Alert name="Instant Coffee 3-in-1" stock="7 left"/><Alert name="Brown Sugar 1kg" stock="Out of stock"/><Alert name="Cooking Oil 1L" stock="4 left"/></div><button className="secondary full" onClick={()=>setView("stock")}>Review stock</button></section></div><section className="panel"><Head title="Price pulse" sub="Current prices and public visibility" action="Open pricing" onClick={()=>setView("pricing")}/><div className="pulse-row"><Stat label="Average listed price" value="₱42.80"/><Stat label="Price changes" value="9" sub="this week"/><Stat label="Fresh listings" value="94%" sub="under 7 days"/><Stat label="Public visibility" value="On" sub="customers can compare" green/></div></section></>}
function Head({title,sub,action,onClick}:{title:string;sub:string;action?:string;onClick?:()=>void}){return <div className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div>{action&&<button className="text-button" onClick={onClick}>{action}<Icon name="arrow"/></button>}</div>}
function Metric({label,value,detail,warning}:{label:string;value:string;detail:string;warning?:boolean}){return <div className="metric"><div className="metric-icon"><Icon name={warning?"bell":"box"}/></div><span>{label}</span><strong>{value}</strong><small className={warning?"warn":""}>{detail}</small></div>}
function Stat({label,value,sub,green}:{label:string;value:string;sub?:string;green?:boolean}){return <div><span>{label}</span><strong className={green?"green":""}>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Movement({m}:{m:string[]}){return <div className="movement"><span className="time">{m[0]}</span><span className={"movement-type "+m[1].toLowerCase()}>{m[1]}</span><div className="movement-name"><strong>{m[2]}</strong><small>Recorded by {m[4]}</small></div><strong className={m[3].startsWith("-")?"negative":"positive"}>{m[3]}</strong></div>}
function Alert({name,stock}:{name:string;stock:string}){return <div className="alert"><i className="alert-dot"/><div><strong>{name}</strong><small>{stock}</small></div><Icon name="arrow"/></div>}
function Catalog({filtered,query,setQuery}:{filtered:typeof products;query:string;setQuery:(v:string)=>void}){return <><div className="hero-row"><div><p className="eyebrow">ITEM MASTER</p><h1>Catalog & Items</h1><p className="muted">Shared products stay separate from each SME's item listing.</p></div><button className="primary"><Icon name="plus"/> Add item</button></div><div className="toolbar"><div className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product, brand, or category"/></div><button className="secondary">All categories</button><button className="secondary">Active only</button></div><section className="panel table-panel"><Head title="Items" sub={filtered.length+" showing"}/><div className="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(p=><tr key={p.name}><td><strong>{p.name}</strong><small>{p.brand}</small></td><td>{p.category}</td><td><strong>₱{p.price.toFixed(2)}</strong></td><td>{p.stock}</td><td><span className={"status "+p.status.toLowerCase().replaceAll(" ","-")}>{p.status}</span></td><td><button className="kebab">•••</button></td></tr>)}</tbody></table></div></section></>}
function Pricing(){return <><div className="hero-row"><div><p className="eyebrow">PRICE CONTROL</p><h1>Pricing</h1><p className="muted">Every price change is attributable and remains in the history.</p></div><button className="primary"><Icon name="plus"/> Change price</button></div><div className="metric-grid three"><Metric label="Changes this week" value="9" detail="2 more than last week"/><Metric label="Average price" value="₱42.80" detail="Across active items"/><Metric label="Freshness" value="94%" detail="Updated within 7 days"/></div><section className="panel table-panel"><Head title="Recent price changes" sub="Corrections remain visible in the audit trail."/><div className="table-wrap"><table><thead><tr><th>Item</th><th>Previous</th><th>New price</th><th>Changed</th><th>By</th><th>Reason</th></tr></thead><tbody>{[["Premium Sardines 155g","₱30.00","₱32.50","Today, 9:31 AM","Mikie Ann","Supplier increase"],["Instant Coffee 3-in-1","₱8.00","₱8.50","Yesterday","Rojean Mae","Cost update"],["Laundry Detergent 65g","₱15.00","₱14.00","Oct 2","Carlo Hilo","Correction"]].map(r=><tr key={r.join("")}>{r.map((x,i)=><td key={x}>{i===0||i===2?<strong>{x}</strong>:x}</td>)}</tr>)}</tbody></table></div></section></>}
function Stock(){return <><div className="hero-row"><div><p className="eyebrow">STOCK CONTROL</p><h1>Stock</h1><p className="muted">Sales, restocks, losses, spoilage, and adjustments form the movement trail.</p></div><button className="primary"><Icon name="plus"/> Record movement</button></div><div className="metric-grid three"><Metric label="On hand" value="1,284" detail="Units across active items"/><Metric label="Low stock" value="7" detail="At or below reorder level" warning/><Metric label="Movements today" value="31" detail="27 sales · 4 adjustments"/></div><section className="panel"><Head title="Movement history" sub="Permanent operational trail" action="Filter"/><div className="movement-list">{[...movements,["Yesterday","SPOILAGE","Brown Sugar 1kg","-2","Manager"]].map(m=><Movement key={m.join("-")} m={m}/>)}</div></section></>}
function Reports(){return <><div className="hero-row"><div><p className="eyebrow">INSIGHTS</p><h1>Reports</h1><p className="muted">Management indicators built from price and stock records.</p></div><button className="secondary">Last 30 days ▾</button></div><div className="report-grid"><Report title="Gross margin signal" value="18.4%" bars/><Report title="Units moved" value="3,842" bars/><Report title="Price change frequency" value="24 changes" wide/></div></>}
function Report({title,value,bars,wide}:{title:string;value:string;bars?:boolean;wide?:boolean}){return <section className={"panel report-card"+(wide?" wide":"")}><span>{title}</span><strong>{value}</strong><div className={bars?"fake-chart":"line"}>{[1,2,3,4,5,6,7,8].map((x)=><i key={x}/>)}</div><small>Based on recorded SME MIS activity</small></section>}
function PublicLookup(){return <><div className="public-head"><div className="public-logo"><div className="brand-mark">S</div><strong>SME MIS</strong><span>Price lookup</span></div><h1>Compare prices near you.</h1><p className="muted">Current listed prices, freshness, and availability from participating stores.</p></div><div className="public-search search"><Icon name="search"/><input placeholder="Search a product, brand, or barcode"/><button>Search</button></div><div className="lookup-grid">{products.slice(0,3).map(p=><article className="lookup-card" key={p.name}><div className="product-thumb">{p.name[0]}</div><div className="lookup-info"><span>{p.category}</span><h2>{p.name}</h2><p>{p.brand}</p><strong>₱{p.price.toFixed(2)}</strong><small>Freshness: today · {p.status}</small></div><button className="icon-button"><Icon name="arrow"/></button></article>)}</div></>}
